<?php
session_start();
require_once('../db.php');

if (!isset($_SESSION['user_id'])) {
    header("Location: ../login.php");
    exit();
}
require_once '../includes/permissions.php';
require_permission($conn, 'exhibit_view');

if (!isset($_GET['exhibit_id'])) {
    die("Exhibit ID not specified.");
}

$exhibit_id = intval($_GET['exhibit_id']);

// Fetch Exhibit Details
$stmt = $conn->prepare("SELECT exhibit_ref, job_id FROM exhibits WHERE exhibit_id = ?");
$stmt->bind_param("i", $exhibit_id);
$stmt->execute();
$stmt->bind_result($exhibit_ref, $job_id);
if (!$stmt->fetch()) {
    die("Exhibit not found.");
}
$stmt->close();

// Fetch every saved receipt covering this exhibit, newest first.
$receipts = [];
$recStmt = $conn->prepare("
    SELECT er.receipt_id, er.receipt_type, er.booked_out_to, er.generated_at,
           CONCAT(u.first_name, ' ', u.last_name) AS generated_by_name
    FROM exhibit_receipt_items eri
    JOIN exhibit_receipts er ON eri.receipt_id = er.receipt_id
    LEFT JOIN users u ON er.generated_by = u.id
    WHERE eri.exhibit_id = ?
    ORDER BY er.generated_at DESC, er.receipt_id DESC
");
$recStmt->bind_param("i", $exhibit_id);
$recStmt->execute();
$recResult = $recStmt->get_result();
while ($row = $recResult->fetch_assoc()) {
    $receipts[] = $row;
}
$recStmt->close();

$typeLabels = [
    'in'     => 'Book In',
    'out'    => 'Book Out',
    'return' => 'Book Back In',
];

include('../header.php');
?>

<style>
    .container {
        max-width: 1000px;
        margin: 130px auto 40px auto;
        background: var(--polaris-surface);
        padding: 30px;
        border-radius: 8px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
        color: var(--polaris-gray-e0);
        font-family: 'Segoe UI', Arial, sans-serif;
    }

    h2 {
        font-size: 1.8em;
        margin-bottom: 20px;
        color: var(--polaris-text);
        border-bottom: 2px solid var(--polaris-border-hover);
        padding-bottom: 10px;
    }

    table {
        width: 100%;
        border-collapse: separate;
        border-spacing: 0;
        margin-top: 20px;
        background: var(--polaris-divider);
        border-radius: 8px;
        overflow: hidden;
    }

    th,
    td {
        padding: 12px 15px;
        text-align: left;
        border-bottom: 1px solid var(--polaris-border);
    }

    th {
        background: var(--polaris-panel-alt);
        color: var(--polaris-text);
        font-weight: 600;
        text-transform: uppercase;
        font-size: 0.9em;
    }

    td {
        background: var(--polaris-surface-alt);
        font-size: 0.95em;
    }

    tr:last-child td {
        border-bottom: none;
    }

    tr:hover td {
        background: var(--polaris-panel-alt);
        transition: background 0.2s ease;
    }

    .no-receipts {
        font-style: italic;
        color: var(--polaris-text-faint);
        padding: 20px;
        text-align: center;
    }

    .view-btn,
    .back-btn {
        display: inline-block;
        background: var(--polaris-accent);
        color: var(--polaris-text);
        padding: 5px 10px;
        text-decoration: none;
        border-radius: 3px;
        font-size: 14px;
        transition: background 0.3s ease;
    }

    .view-btn:hover,
    .back-btn:hover {
        background: var(--polaris-accent-hover);
    }

    .back-btn {
        margin-top: 20px;
    }

    @media (max-width: 768px) {
        .container {
            padding: 15px;
            margin: 0 10px;
        }

        table {
            font-size: 0.9em;
        }

        th,
        td {
            padding: 10px;
        }
    }
    </style>

    <div class="container">
        <h2>Receipts for Exhibit: <?php echo htmlspecialchars($exhibit_ref); ?></h2>

        <?php if (!empty($receipts)): ?>
        <table>
            <thead>
                <tr>
                    <th>Timestamp</th>
                    <th>Type</th>
                    <th>Generated By</th>
                    <th>Notes</th>
                    <th>Receipt</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($receipts as $rec): ?>
                <tr>
                    <td><?php echo htmlspecialchars($rec['generated_at']); ?></td>
                    <td><?php echo htmlspecialchars($typeLabels[$rec['receipt_type']] ?? $rec['receipt_type']); ?></td>
                    <td><?php echo htmlspecialchars($rec['generated_by_name'] ?? ''); ?></td>
                    <td>
                        <?php if ($rec['receipt_type'] === 'out'): ?>
                        Booked Out To: <?php echo htmlspecialchars($rec['booked_out_to'] ?? ''); ?>
                        <?php elseif ($rec['receipt_type'] === 'return'): ?>
                        Returned By: <?php echo htmlspecialchars($rec['booked_out_to'] ?? ''); ?>
                        <?php endif; ?>
                    </td>
                    <td>
                        <a class="view-btn" target="_blank"
                            href="view_receipt.php?receipt_id=<?php echo $rec['receipt_id']; ?>">View</a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php else: ?>
        <p class="no-receipts">No receipts have been generated for this exhibit.</p>
        <?php endif; ?>

        <a href="job.php?job_id=<?php echo $job_id; ?>" class="back-btn">Back to Case</a>
    </div>
</body>

</html>
